#!/bin/sh
# Medusa v2 container entrypoint (server AND worker services share this image).
#
# Ordering is the whole point of this script:
#   0. wait for Postgres to accept connections
#   1. migrations   (medusa db:migrate — idempotent, safe on every boot) — server/shared only
#   2. worker waits for the schema (the server owns migrations on fresh deploys)
#   3. admin user   (bootstrap once; retries are no-ops when the user exists)
#   4. serve        (medusa start)
set -e

# Worker mode: explicit MEDUSA_WORKER_MODE wins; otherwise derive from the
# Railway service name (…worker… -> worker, …server… -> server, else shared)
# so the template needs no deploy-time input.
MODE="${MEDUSA_WORKER_MODE:-}"
if [ -z "$MODE" ]; then
  case "${RAILWAY_SERVICE_NAME:-}" in
    *worker*) MODE="worker" ;;
    *server*) MODE="server" ;;
    *) MODE="shared" ;;
  esac
fi
export MEDUSA_WORKER_MODE="$MODE"
cd /app/.medusa/server

echo "[start] worker mode: ${MODE}"

# 0. Wait until Postgres accepts connections (fresh deploys race provisioning).
i=0
until node -e "
const { Client } = require('pg');
const c = new Client({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
c.connect().then(() => c.end()).then(() => process.exit(0)).catch(() => process.exit(1));
" 2>/dev/null; do
  i=$((i + 1))
  if [ "$i" -ge 60 ]; then
    echo "[start] Postgres not reachable after 5 minutes — failing." >&2
    exit 1
  fi
  sleep 5
done
echo "[start] Postgres reachable"

if [ "${MIGRATE_ON_BOOT:-true}" = "true" ] && [ "${MODE}" != "worker" ]; then
  echo "[start] running migrations (medusa db:migrate)..."
  npm run predeploy
  echo "[start] migrations complete"
fi

if [ "${MODE}" = "worker" ]; then
  # The server service owns migrations; on a fresh deploy the worker must wait
  # for the schema to exist before its modules load (payment_provider is
  # created by the core migrations — a reliable readiness marker).
  i=0
  until node -e "
const { Client } = require('pg');
const c = new Client({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
c.connect()
  .then(() => c.query(\"SELECT to_regclass('public.payment_provider') IS NOT NULL AS ok\"))
  .then((r) => { const ok = r.rows[0] && r.rows[0].ok; return c.end().then(() => process.exit(ok ? 0 : 1)); })
  .catch(() => process.exit(1));
" 2>/dev/null; do
    i=$((i + 1))
    if [ "$i" -ge 60 ]; then
      echo "[start] schema not ready after 5 minutes — failing (is the medusa-server service deploying?)." >&2
      exit 1
    fi
    sleep 5
  done
  echo "[start] schema ready (migrations applied by server)"
fi

# Admin bootstrap: needs MEDUSA_ADMIN_PASSWORD (auto-generated by the
# Railway template; retrieve it from the medusa-server service variables).
# MEDUSA_ADMIN_EMAIL is optional and defaults to admin@example.com.
ADMIN_EMAIL="${MEDUSA_ADMIN_EMAIL:-admin@example.com}"

if [ "${MODE}" != "worker" ] && [ -n "${MEDUSA_ADMIN_PASSWORD:-}" ]; then
  echo "[start] ensuring admin user ${ADMIN_EMAIL} exists..."
  npx --no-install medusa user -e "${ADMIN_EMAIL}" -p "${MEDUSA_ADMIN_PASSWORD}" \
    || echo "[start] admin user not created (probably already exists) — continuing"
fi

echo "[start] starting Medusa..."
exec npm run start
